language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install urllib3==1.26.6

before_script:
  - sudo apt update
  - sudo apt upgrade sqlite3
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls

after_script: 
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "swe1-app"
  env: "swe1-app-python-env"
  bucket_name: "elastic-beanstalk-test-swe1"
  on:
    branch: main