language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before script:
  - sudo apt-get update
  - sudo apt-get upgrade sqlite3
  - python manage.py makemigrations
  - python manage.py migrate
  - black .

script:
  - black --check .
  - flake8 .
  - coverage run polls/tests.py